#上传路径配置
brightease:
  filePath: d:/
  tempUpLoadPath: d:/

#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_car_document?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 123456     # 密码（默认为空）
    timeout: 6000ms # 连接超时时长（ timeout*60*60）
    jedis:
      pool:
        max-active: 500     # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10        # 连接池中的最大空闲连接
        min-idle: 5         # 连接池中的最小空闲连接
#ftp
ftp:
  host: 192.168.0.110
  port: 22
  username: root
  password: 1qazXSW@
  defatultport: 22
  serverpath: carsfile
  req:
    url: 192.168.0.110